version: "3.9"

services:

  capture:
    container_name: trap-capture
    build:
      context: .
    privileged: true
    command: python3 capture.py
#    env_file:
#      - dockerfiles/.env
    volumes:
      - ./:/src/
      - /sys/class/gpio:/sys/class/gpio

  upload:
    container_name: trap-upload
    labels:
      name: Upload
      description: Python 3 using Jupyter Notebooks
    build:
      context: .
    command: echo &HOME
#    env_file:
#      - dockerfiles/.env
    volumes:
      - ./:/src/
      - /sys/class/gpio:/sys/class/gpio
