version: "2.3"

services:

  capture:
    container_name: trap-capture
    labels:
      name: Capture
      description: Python 3 using Jupyter Notebooks
    build:
      context: ..
    runtime: nvidia
    privileged: true
    command: python3
    environment:
        - SITE=${SITE}
        - TOKEN=${TOKEN}
        - DISPLAY=${DISPLAY}
    ipc: host
    network_mode: "host"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./:/src/
      - /sys/class/gpio:/sys/class/gpio
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /tmp/argus_socket:/tmp/argus_socket


  upload:
    container_name: trap-upload
    labels:
      name: Upload
      description: Python 3 using Jupyter Notebooks
    build:
      context: ..
    command: echo &HOME
    environment:
      - SITE=${SITE}
      - TOKEN=${TOKEN}
    volumes:
      - ./:/src/
      - /sys/class/gpio:/sys/class/gpio
